In [5]:
a = [["2000-01-01", 114], ["1919-08-10", 514]]
print([int(x) for x in a[0][0].split('-')])

[2000, 1, 1]


In [15]:
import numpy as np
seq_number = np.array(
    [112., 118., 132., 129., 121., 135., 148., 148., 136., 119., 104.,
        118., 115., 126., 141., 135., 125., 149., 170., 170., 158., 133.,
        114., 140., 145., 150., 178., 163., 172., 178., 199., 199., 184.,
        162., 146., 166., 171., 180., 193., 181., 183., 218., 230., 242.,
        209., 191., 172., 194., 196., 196., 236., 235., 229., 243., 264.,
        272., 237., 211., 180., 201., 204., 188., 235., 227., 234., 264.,
        302., 293., 259., 229., 203., 229., 242., 233., 267., 269., 270.,
        315., 364., 347., 312., 274., 237., 278., 284., 277., 317., 313.,
        318., 374., 413., 405., 355., 306., 271., 306., 315., 301., 356.,
        348., 355., 422., 465., 467., 404., 347., 305., 336., 340., 318.,
        362., 348., 363., 435., 491., 505., 404., 359., 310., 337., 360.,
        342., 406., 396., 420., 472., 548., 559., 463., 407., 362., 405.,
        417., 391., 419., 461., 472., 535., 622., 606., 508., 461., 390.,
        432.], dtype=np.float32)
# assert seq_number.shape == (144, )
# plt.plot(seq_number)
# plt.ion()
# plt.pause(1)
seq_number = seq_number[:, np.newaxis]

# print(repr(seq))
# 1949~1960, 12 years, 12*12==144 month
seq_year = np.arange(12)
seq_month = np.arange(12)
seq_year_month = np.transpose(
    [np.repeat(seq_year, len(seq_month)),
        np.tile(seq_month, len(seq_year))],
)  # Cartesian Product

seq = np.concatenate((seq_number, seq_year_month), axis=1)

# normalization
# seq = (seq - seq.mean(axis=0)) / seq.std(axis=0)

In [16]:
print(seq)

[[112.   0.   0.]
 [118.   0.   1.]
 [132.   0.   2.]
 [129.   0.   3.]
 [121.   0.   4.]
 [135.   0.   5.]
 [148.   0.   6.]
 [148.   0.   7.]
 [136.   0.   8.]
 [119.   0.   9.]
 [104.   0.  10.]
 [118.   0.  11.]
 [115.   1.   0.]
 [126.   1.   1.]
 [141.   1.   2.]
 [135.   1.   3.]
 [125.   1.   4.]
 [149.   1.   5.]
 [170.   1.   6.]
 [170.   1.   7.]
 [158.   1.   8.]
 [133.   1.   9.]
 [114.   1.  10.]
 [140.   1.  11.]
 [145.   2.   0.]
 [150.   2.   1.]
 [178.   2.   2.]
 [163.   2.   3.]
 [172.   2.   4.]
 [178.   2.   5.]
 [199.   2.   6.]
 [199.   2.   7.]
 [184.   2.   8.]
 [162.   2.   9.]
 [146.   2.  10.]
 [166.   2.  11.]
 [171.   3.   0.]
 [180.   3.   1.]
 [193.   3.   2.]
 [181.   3.   3.]
 [183.   3.   4.]
 [218.   3.   5.]
 [230.   3.   6.]
 [242.   3.   7.]
 [209.   3.   8.]
 [191.   3.   9.]
 [172.   3.  10.]
 [194.   3.  11.]
 [196.   4.   0.]
 [196.   4.   1.]
 [236.   4.   2.]
 [235.   4.   3.]
 [229.   4.   4.]
 [243.   4.   5.]
 [264.   4.   6.]
 [272.   4

In [18]:
data_x = seq[:-1, :]
data_y = seq[+1:, 0]
print(data_x)
print(data_y)

[[112.   0.   0.]
 [118.   0.   1.]
 [132.   0.   2.]
 [129.   0.   3.]
 [121.   0.   4.]
 [135.   0.   5.]
 [148.   0.   6.]
 [148.   0.   7.]
 [136.   0.   8.]
 [119.   0.   9.]
 [104.   0.  10.]
 [118.   0.  11.]
 [115.   1.   0.]
 [126.   1.   1.]
 [141.   1.   2.]
 [135.   1.   3.]
 [125.   1.   4.]
 [149.   1.   5.]
 [170.   1.   6.]
 [170.   1.   7.]
 [158.   1.   8.]
 [133.   1.   9.]
 [114.   1.  10.]
 [140.   1.  11.]
 [145.   2.   0.]
 [150.   2.   1.]
 [178.   2.   2.]
 [163.   2.   3.]
 [172.   2.   4.]
 [178.   2.   5.]
 [199.   2.   6.]
 [199.   2.   7.]
 [184.   2.   8.]
 [162.   2.   9.]
 [146.   2.  10.]
 [166.   2.  11.]
 [171.   3.   0.]
 [180.   3.   1.]
 [193.   3.   2.]
 [181.   3.   3.]
 [183.   3.   4.]
 [218.   3.   5.]
 [230.   3.   6.]
 [242.   3.   7.]
 [209.   3.   8.]
 [191.   3.   9.]
 [172.   3.  10.]
 [194.   3.  11.]
 [196.   4.   0.]
 [196.   4.   1.]
 [236.   4.   2.]
 [235.   4.   3.]
 [229.   4.   4.]
 [243.   4.   5.]
 [264.   4.   6.]
 [272.   4

In [22]:
inp_dim = 3
out_dim = 1
batch_size = 12 * 4

'''load data'''
data = seq
data_x = data[:-1, :]
data_y = data[+1:, 0]
assert data_x.shape[1] == inp_dim

train_size = int(len(data_x) * 0.75)

train_x = data_x[:train_size]
train_y = data_y[:train_size]
train_x = train_x.reshape((train_size, inp_dim))
train_y = train_y.reshape((train_size, out_dim))

In [23]:
print(train_x)
print(train_y)

[[112.   0.   0.]
 [118.   0.   1.]
 [132.   0.   2.]
 [129.   0.   3.]
 [121.   0.   4.]
 [135.   0.   5.]
 [148.   0.   6.]
 [148.   0.   7.]
 [136.   0.   8.]
 [119.   0.   9.]
 [104.   0.  10.]
 [118.   0.  11.]
 [115.   1.   0.]
 [126.   1.   1.]
 [141.   1.   2.]
 [135.   1.   3.]
 [125.   1.   4.]
 [149.   1.   5.]
 [170.   1.   6.]
 [170.   1.   7.]
 [158.   1.   8.]
 [133.   1.   9.]
 [114.   1.  10.]
 [140.   1.  11.]
 [145.   2.   0.]
 [150.   2.   1.]
 [178.   2.   2.]
 [163.   2.   3.]
 [172.   2.   4.]
 [178.   2.   5.]
 [199.   2.   6.]
 [199.   2.   7.]
 [184.   2.   8.]
 [162.   2.   9.]
 [146.   2.  10.]
 [166.   2.  11.]
 [171.   3.   0.]
 [180.   3.   1.]
 [193.   3.   2.]
 [181.   3.   3.]
 [183.   3.   4.]
 [218.   3.   5.]
 [230.   3.   6.]
 [242.   3.   7.]
 [209.   3.   8.]
 [191.   3.   9.]
 [172.   3.  10.]
 [194.   3.  11.]
 [196.   4.   0.]
 [196.   4.   1.]
 [236.   4.   2.]
 [235.   4.   3.]
 [229.   4.   4.]
 [243.   4.   5.]
 [264.   4.   6.]
 [272.   4

In [24]:
batch_var_x, batch_var_y = [],[]
for i in range(batch_size):
    j = train_size - i
    batch_var_x.append(train_x[j:])
    batch_var_y.append(train_y[j:])
print(batch_var_x)
print(batch_var_y)

[array([], shape=(0, 3), dtype=float64), array([[305.,   8.,  10.]]), array([[347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[404.,   8.,   8.],
       [347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[467.,   8.,   7.],
       [404.,   8.,   8.],
       [347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[465.,   8.,   6.],
       [467.,   8.,   7.],
       [404.,   8.,   8.],
       [347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[422.,   8.,   5.],
       [465.,   8.,   6.],
       [467.,   8.,   7.],
       [404.,   8.,   8.],
       [347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[355.,   8.,   4.],
       [422.,   8.,   5.],
       [465.,   8.,   6.],
       [467.,   8.,   7.],
       [404.,   8.,   8.],
       [347.,   8.,   9.],
       [305.,   8.,  10.]]), array([[348.,   8.,   3.],
       [355.,   8.,   4.],
       [422.,   8.,   5.],
       [465.,   8.,   6.],
       [467.,   8.,   7.],
       [404.,   8.,   8.],
       [347.,   8.,   9.],


In [4]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b=np.array([[1],[2],[3],[4]])
c=np.array([[5],[6],[7],[8]])
print(np.concatenate((a,b,c),axis=1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [29]:
import torch
from torch.nn.utils.rnn import pad_sequence


In [27]:
a = torch.ones(1,5)
b = torch.ones(1,6)
c = torch.ones(1,7)

print(a,b,c)
print(pad_sequence([a,b,c]))

tensor([[1., 1., 1., 1., 1.]]) tensor([[1., 1., 1., 1., 1., 1.]]) tensor([[1., 1., 1., 1., 1., 1., 1.]])


RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 1

In [50]:
import numpy as np
from config import param, paths, hyper
dictMain = np.load(paths['Data_Mainland'], allow_pickle=True).item()
dictProv = np.load(paths['Data_Province'], allow_pickle=True).item()
print(len(dictProv['Beijing']))
print(len(dictMain['confirmed']))

752
752


In [43]:
seqence_size = 4
batch_size = 139
input_size = 1
hidden_size = 2
num_layers = 3

inputX = torch.randn(seqence_size,batch_size,input_size)
rnnLSTM = torch.nn.LSTM(input_size,hidden_size,num_layers, batch_first=False)
h_0 = torch.randn(num_layers,batch_size, hidden_size)
c_0 = torch.randn(num_layers,batch_size, hidden_size)


In [44]:
output, (h_n, c_n) = rnnLSTM(inputX, (h_0, c_0))

In [48]:
print(output[0])

tensor([[ 3.7738e-01,  1.7881e-01],
        [-1.5151e-01, -1.6831e-01],
        [-2.9090e-01,  1.9798e-01],
        [-6.9997e-02,  2.9964e-02],
        [ 5.2195e-01,  9.9284e-02],
        [-3.0323e-01,  1.3370e-01],
        [-1.1502e-01,  3.7616e-01],
        [ 6.3408e-02,  1.4606e-01],
        [ 3.3497e-01,  9.0833e-02],
        [ 4.4227e-01,  1.5133e-01],
        [ 7.6269e-02,  1.3150e-01],
        [ 3.3389e-01,  8.0043e-02],
        [-2.0868e-01, -1.2321e-01],
        [ 2.5165e-01,  2.3062e-02],
        [-2.0776e-01,  2.2958e-02],
        [ 2.4320e-01,  1.8749e-01],
        [-3.8250e-02, -2.6222e-02],
        [-2.7142e-01, -6.9354e-02],
        [-1.8773e-01,  2.4990e-01],
        [ 6.1844e-01,  9.1768e-02],
        [ 1.0990e-02,  1.0021e-01],
        [-1.7362e-01,  7.0534e-02],
        [-8.8312e-02,  1.9268e-02],
        [ 4.5867e-01,  5.3960e-02],
        [-2.6345e-01,  1.4497e-01],
        [-1.4456e-01, -2.2373e-02],
        [-9.3590e-02, -2.1412e-01],
        [ 5.1651e-01,  6.016

In [2]:
a = {'a':1,'b':2,'c':3,}
print(len(a))
for name in a:
    print(name, a[name])

3
a 1
b 2
c 3
